stepback: true
pre:
  - command: expansions.fetch
    params:
      keys:
        - local_key: "aws_key"
          remote_key: "project_aws_key"
        - local_key: "aws_secret"
          remote_key: "project_aws_secret"
  - command: shell.exec
    params:
      script: |
        set -o verbose
        rm -rf "libbson"
        rm -rf /data/db
        mkdir -p /data/db
post:
  - command: shell.exec
    params:
      script: |
        set -o verbose
        ${killall_mci|pkill -9 mongod; pkill -9 mongos}

## tasks 
tasks: 
- name: compile
  commands: 
    - command: git.get_project
      params:
        directory: "libbson"
    - command: git.apply_patch
      params:
        directory: "libbson"
    - command: shell.exec
      params:
        working_dir: "libbson"
        script: |
          set -o verbose
          set -o errexit
          ./autogen.sh
          make ${compile_flags}
          tar -czvf ../libbson.tar.gz .
    - command: s3.put
      params:
        aws_key: ${aws_key}
        aws_secret: ${aws_secret}
        remote_file: libbson/${build_variant}/${revision}/artifacts/${build_id}.tar.gz
        bucket: mciuploads
        local_file: libbson.tar.gz
        permissions: public-read
        content_type: ${content_type|application/x-gzip}

- name: "make check"
  depends_on:
    - name: "compile"
  commands:
    - command: shell.exec
      params:
        script: |
            mkdir libbson
    - command: shell.exec
      params:
        working_dir: "libbson"
        script: |
            set -o verbose
            set -o errexit
            # MCI's S3 mechanism doesn't support symlinks
            curl http://s3.amazonaws.com/mciuploads/libbson/${build_variant}/${revision}/artifacts/${build_id}.tar.gz -o ${build_id}.tar.gz --silent
            tar -xzf ${build_id}.tar.gz
            make check

buildvariants:
- name: ubuntu-1404
  display_name: "Ubuntu-1404"
  expansions: 
    compile_flags: -j$(grep -c ^processor /proc/cpuinfo)
    mongo_url: "http://downloads.mongodb.com/linux/mongodb-linux-x86_64-enterprise-ubuntu1404-latest.tgz"
    mongodb_args: "--dbpath /data/db --nopreallocj --setParameter=enableTestCommands=1 &"
  run_on: 
    - ubuntu1404-test
  tasks:
  - name: compile
  - name: "make check"
